source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/LexoVideo/lexo-dev-specs.git'

platform :ios, '13.0'

target 'DecryptDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DecryptDemo
  pod 'DRMLib'
  pod 'SnapKit'

end
